import express from "express";import helmet from "helmet";import cors from "cors";import morgan from "morgan";import jwt from "jsonwebtoken";import {PrismaClient} from "@prisma/client";import {z} from "zod";
const app=express(),prisma=new PrismaClient();const PORT=process.env.PORT||3001,JWT_SECRET=process.env.JWT_SECRET||"dev-secret",ADMIN_USERNAME=process.env.ADMIN_USERNAME||"admin",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"change-me-strong-password";
app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(morgan("tiny"));app.use(express.json({limit:"10mb"}));
const schema=z.object({title:z.string().min(1),summary:z.string().optional().default(""),body:z.string().optional().default(""),category:z.string().optional().default("未分類"),tags:z.array(z.string()).optional().default([])});
function slugify(t){return String(t||"article").trim().toLowerCase().replace(/[^\w\u3040-\u30ff\u3400-\u9fff-]+/g,"-").replace(/^-+|-+$/g,"")||`article-${Date.now()}`}
function auth(req,res,next){const h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):"";if(!t)return res.status(401).json({error:"ログインしてください"});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:"ログイン期限が切れています"})}}
function structure(raw){const text=String(raw||"").trim();const lines=text.split("\n").map(l=>l.trim()).filter(Boolean);let title=(lines.find(l=>!l.startsWith("root@")&&!l.startsWith("{"))||"新しいナレッジ").replace(/^#+\s*/,"").slice(0,48);if(text.includes("AI Hub")&&text.match(/Docker|docker/))title="AI Hub構築・運用ログ";if(text.match(/502|Bad Gateway/i))title="AI Hub 502エラー対応ログ";if(text.includes("git pull"))title="AI Hub GitHub更新ログ";const rules=[["Docker",/docker/i],["GitHub",/github|git pull|git clone/i],["Nginx",/nginx|80番|gateway/i],["PostgreSQL",/postgres|prisma/i],["React",/react|frontend/i],["Backend",/backend|api/i],["Proxmox",/proxmox|lxc|コンテナ/i],["トラブルシュート",/error|エラー|失敗|502|failed|fatal/i],["AI Hub",/ai hub|aihub/i]];const tags=[...new Set(rules.filter(([,r])=>r.test(text)).map(([t])=>t))];if(!tags.length)tags.push("ナレッジ");const commands=lines.filter(l=>/^(cd |docker |git |curl |cat |grep |nano |systemctl |apt |rm |mkdir |unzip )/.test(l)||l.startsWith("root@")).slice(0,30);const troubles=lines.filter(l=>/error|failed|fatal|502|Bad Gateway|失敗|エラー|できない|動かない|アクセスできない/i.test(l)).slice(0,20);const summary=text.replace(/\s+/g," ").slice(0,140);const body=["## 概要",summary||"作業ログをナレッジ化しました。","","## 元メモ",text,"",commands.length?"## コマンド":"",...commands.map(c=>`- ${c}`),"",troubles.length?"## トラブル・注意点":"",...troubles.map(t=>`- ${t}`),"","## 次に確認すること","- 保存後に検索できるか確認する","- 関連タグで絞り込めるか確認する"].filter(Boolean).join("\n");return{title,summary,category:tags.includes("AI Hub")?"AI Hub":"ナレッジ",tags,body}}
app.get("/api/health",(_,res)=>res.json({ok:true,version:"v1.1.0"}));
app.post("/api/auth/login",(req,res)=>{const{username,password}=req.body||{};if(username!==ADMIN_USERNAME||password!==ADMIN_PASSWORD)return res.status(401).json({error:"ユーザー名またはパスワードが違います"});res.json({token:jwt.sign({username,role:"admin"},JWT_SECRET,{expiresIn:"7d"}),username})});
app.get("/api/articles",async(req,res)=>{const q=String(req.query.q||"").trim().toLowerCase(),category=String(req.query.category||"").trim(),tag=String(req.query.tag||"").trim();const where={status:"published"};if(category)where.category=category;if(tag)where.tags={has:tag};const arts=await prisma.article.findMany({where,orderBy:{updatedAt:"desc"}});const filtered=q?arts.filter(a=>{const s=[a.title,a.summary,a.body,a.category,...(a.tags||[])].join(" ").toLowerCase();return q.split(/\s+/).every(w=>s.includes(w))}):arts;res.json({articles:filtered})});
app.get("/api/articles/:id",async(req,res)=>{const a=await prisma.article.findFirst({where:{OR:[{id:req.params.id},{slug:req.params.id}],status:"published"}});if(!a)return res.status(404).json({error:"記事が見つかりません"});res.json(a)});
app.post("/api/articles",auth,async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:"入力内容を確認してください"});const d=p.data;let slug=slugify(d.title),base=slug,n=2;while(await prisma.article.findUnique({where:{slug}}))slug=`${base}-${n++}`;res.json(await prisma.article.create({data:{...d,slug,tags:d.tags.map(t=>t.trim()).filter(Boolean)}}))});
app.put("/api/articles/:id",auth,async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:"入力内容を確認してください"});const ex=await prisma.article.findFirst({where:{OR:[{id:req.params.id},{slug:req.params.id}]}});if(!ex)return res.status(404).json({error:"記事が見つかりません"});const d=p.data;res.json(await prisma.article.update({where:{id:ex.id},data:{...d,tags:d.tags.map(t=>t.trim()).filter(Boolean)}}))});
app.delete("/api/articles/:id",auth,async(req,res)=>{const ex=await prisma.article.findFirst({where:{OR:[{id:req.params.id},{slug:req.params.id}]}});if(!ex)return res.status(404).json({error:"記事が見つかりません"});await prisma.article.update({where:{id:ex.id},data:{status:"deleted"}});res.json({ok:true})});
app.post("/api/knowledge/structure",auth,(req,res)=>res.json(structure(req.body?.text||"")));
app.post("/api/knowledge/save",auth,async(req,res)=>{const d=structure(req.body?.text||"");let slug=slugify(d.title),base=slug,n=2;while(await prisma.article.findUnique({where:{slug}}))slug=`${base}-${n++}`;res.json(await prisma.article.create({data:{...d,slug}}))});
app.get("/api/export",auth,async(_,res)=>res.json({version:"v1.1.0",exportedAt:new Date().toISOString(),articles:await prisma.article.findMany({where:{status:"published"},orderBy:{updatedAt:"desc"}})}));
app.get("/api/meta",async(_,res)=>{const arts=await prisma.article.findMany({where:{status:"published"}});res.json({articles:arts.length,categories:[...new Set(arts.map(a=>a.category).filter(Boolean))].sort(),tags:[...new Set(arts.flatMap(a=>a.tags||[]))].sort(),version:"v1.1.0"})});
app.listen(PORT,()=>console.log(`AI Hub backend v1.1.0 running on port ${PORT}`));
